name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Change to your branch name if needed
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install  # Change if using yarn/pnpm

      - name: Build Project
        run: npm run build  # Change if using a different build command

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./dist  # Change if your build output is different (e.g., build/)
          production-branch: main
          deploy-message: "Deployed via GitHub Actions"
          enable-pull-request-comment: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
